name: 🤯 バグ・不具合修正
description: バグなどの不具合を修正する際に使用します
title: "[BUG] "
labels: ["バグ・不具合修正"]
body:
  - type: textarea
    id: bug_summary
    attributes:
      label: 🔍 どんな問題が起きていますか？
      description: 発生している問題を簡潔に説明してください
      placeholder: |
        例：ログインページでメールアドレスを入力してもエラーが表示される
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🤯 どうすれば同じ問題が起きますか？
      description: バグを再現するための手順を教えてください
      placeholder: |
        例：
        1. ログインページにアクセス
        2. メールアドレスとパスワードを入力
        3. ログインボタンをクリック
        4. → エラーメッセージが表示される
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ 本当はどうなるべきですか？
      description: 正常な場合はどのような動作になるべきかを教えてください
      placeholder: |
        例：正しい認証情報を入力した場合、ダッシュボードに移動するべき
    validations:
      required: true

  - type: textarea
    id: environment_and_notes
    attributes:
      label: 📝 その他・補足
      description: 使用環境、スクリーンショット、エラーメッセージなど
      placeholder: |
        例：
        - OS: macOS
        - ブラウザ: Chrome
        - エラーメッセージ: 「認証に失敗しました」
        - スクリーンショット（あれば）
      value: 特になし
    validations:
      required: false
