name: 💡 新規実装
description: 新しい機能の追加・実装を行う際に使用します
title: "[FEATURE] "
labels: ["新規実装"]
body:
  - type: textarea
    id: feature_summary
    attributes:
      label: 🚀 何を作りたいですか？
      description: 実装したい機能を簡潔に説明してください
      placeholder: |
        例：ユーザーがプロフィール画像をアップロードできる機能
    validations:
      required: true

  - type: textarea
    id: why_needed
    attributes:
      label: 💡 なぜ必要ですか？
      description: この機能が必要な理由やユーザーにとっての価値を教えてください
      placeholder: |
        例：ユーザーが自分らしさを表現できるようにして、コミュニティへの参加意欲を高めたい
    validations:
      required: true

  - type: textarea
    id: basic_requirements
    attributes:
      label: 📋 どんな機能が必要ですか？
      description: 必要な機能や要件を箇条書きで記入してください
      placeholder: |
        例：
        - 画像をアップロードできる
        - アップロードした画像をプロフィールに表示する
        - 画像サイズを自動調整する
        - デフォルト画像も用意する
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 いつまでに必要ですか？
      description: この機能の優先度を選択してください
      options:
        - 高（緊急・なるべく早く）
        - 中（重要・計画的に進めたい）
        - 低（余裕があるときに）
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: 📝 その他・補足
      description: 技術的な要望、参考資料、制約事項など、あれば自由に記入してください
      placeholder: |
        例：
        - 参考にしたいサイトやアプリ
        - 技術的な希望（React、Vue.jsなど）
        - 制約や注意点
        - 関連するissue
      value: 特になし
    validations:
      required: false